### ISSUE TITLE
example_mpi_synh5.py doesn't work

### ISSUE THREAD

**Issue by sourceonly** [aasensio/hazel2#15]
Tested on OS
1) GNU/Linux Debian Sid 
2) Mac OS high sierra 10.13.6

Below STDERR is from Debian Sid , 
```
 mpirun -n 2 /opt/python36/bin/python3 example_mpi_synh5.py 
2018-09-23 23:06:22,099 - iterator - INFO - Starting calculation with 1 workers
  0%|                                                                            10%|███████▉                                                                    10%|████████                                                                         | 1/10 [00:00<00:00, 41.59it/s, received=0, sent=1->1]
Traceback (most recent call last):
  File "example_mpi_synh5.py", line 12, in <module>
    iterator.run_all_pixels()
  File "/opt/python36/lib/python3.6/site-packages/hazel-2018.6.7-py3.6-linux-x86_64.egg/hazel/multiprocess.py", line 334, in run_all_pixels
    self.mpi_master_work()
  File "/opt/python36/lib/python3.6/site-packages/hazel-2018.6.7-py3.6-linux-x86_64.egg/hazel/multiprocess.py", line 239, in mpi_master_work
    v.stokes_cycle = data_received[label][k]
KeyError: 'randomization_0'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
I've taken a brief look at the hazel/multiprocessing.py,  there is no data_to_send send back to mpi_master_work from mpi_agent_work while in 'synthesis' mode. (not sure if i understood the code correctly)

**Comment by aasensio** [comment]
You were right. I've fixed it.
