### ISSUE TITLE
Error using spectral line with keyword "XX"

### ISSUE THREAD

**Issue by Hypnus1803** [aasensio/hazel2#31]
At this moment, I am attempting to use Hazel2 to invert spectral line 5250 (spectral line 2 "XX") in the list of lines accepted by Hazel2. When I attempt to run the inversion, I encounter the following error:

`
Traceback (most recent call last):
  File "/media/hypnus1803/DI/Ondrejov/DataSST/20130613/data/hazel/script1.py", line 6, in <module>
    mod = hazel.Model('conf_spot1_3d.ini', working_mode='inversion',rank=iterator.get_rank())
  File "/home/hypnus1803/miniconda3/envs/hazel_env/lib/python3.10/site-packages/hazel-2018.9.22-py3.10-linux-x86_64.egg/hazel/model.py", line 96, in __init__
    self.use_configuration(self.configuration.config_dict)
  File "/home/hypnus1803/miniconda3/envs/hazel_env/lib/python3.10/site-packages/hazel-2018.9.22-py3.10-linux-x86_64.egg/hazel/model.py", line 248, in use_configuration
    self.setup()
  File "/home/hypnus1803/miniconda3/envs/hazel_env/lib/python3.10/site-packages/hazel-2018.9.22-py3.10-linux-x86_64.egg/hazel/model.py", line 366, in setup
    self.init_sir()
  File "/home/hypnus1803/miniconda3/envs/hazel_env/lib/python3.10/site-packages/hazel-2018.9.22-py3.10-linux-x86_64.egg/hazel/model.py", line 1081, in init_sir
    atom[i] = elements[tmp[0].split('=')[1]]
KeyError: 'XX'
`

**Comment by aasensio** [comment]
For some strange reason, the element of line 1 and 2 (5247 and 5250 A) was set to XX instead of FE. It should be solved by now.

**Comment by Hypnus1803** [comment]
Thanks, it is working now.
