### ISSUE TITLE
pyGUI

### ISSUE THREAD

**Issue by reza35** [aasensio/hazel2#5]
I guess this folder is still old. the python routines need "pyhazel" which is the one we created in the previous version. should I create a fake python executable? or you plan to update them?

(rpy3) reza@debian:/data/hazel2/hazel2/pyGUI$ python hazel_pyqt5.py
backend =  Qt5Agg
Traceback (most recent call last):
  File "hazel_pyqt5.py", line 12, in <module>
    from hazel import hazel
  File "/data/hazel2/hazel2/pyGUI/hazel.py", line 2, in <module>
    import pyhazel
ModuleNotFoundError: No module named 'pyhazel'

**Comment by aasensio** [comment]
Yes, it was not implemented. I've been working on this and now it works. There are some things to tune yet, but at least you can play with the GUI.

**Comment by reza35** [comment]
Thank you. It works fine now like in the old version (`python gui.py`) with only one problem I can report:  changing wavelength causes a crash.

**Comment by aasensio** [comment]
I'll work on that. There are still some issues with this and I have to check where is the problem coming from.
